// Default imports
import Head from "next/head";
import styles from "../styles/Home.module.css";
import toolbar from "../styles/Toolbar.module.css";
import NavBar from "../components/navbar";
import clientPromise from "../lib/mongodb";
import Modal from "react-modal";
import { useEffect, useState } from "react";

export default function Home({ appointments, caregivers }) {
  const [data, setData] = useState({
    appointments: JSON.parse(appointments),
    caregivers: JSON.parse(caregivers),
  });

  return (
    <>
      <Head>
        <title>Home - App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className={styles.main}>
        <div className={toolbar.container}>
          <div className={toolbar.buttonContainer}>
            <div className={toolbar.searchContainer}>
              <div className={toolbar.textInput}>
                <select
                  className={toolbar.longSelectButton}
                  onChange={(event) => {}}
                >
                  <option value="monday">Montag</option>
                  <option value="tuesday">Dienstag</option>
                  <option value="wednesday">Mittwoch</option>
                  <option value="thursday">Donnerstag</option>
                  <option value="friday">Freitag</option>
                  <option value="saturday">Samstag</option>
                  <option value="sunday">Sonntag</option>
                </select>
              </div>
            </div>
            <div className={toolbar.buttons}>
              <button className={toolbar.editButton} onClick={() => {}}>
                Öffnen
              </button>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  try {
    const client = await clientPromise;
    const db = client.db("swe-projekt");

    const appointments = await db
      .collection("termine")
      .find({})
      .sort({ _id: -1 })
      .limit(1)
      .toArray();

    const caregivers = await db
      .collection("pflegekraft")
      .find({})
      .sort({ lastname: 1 })
      .toArray();

    return {
      props: {
        appointments: JSON.stringify(appointments),
        caregivers: JSON.stringify(caregivers),
      },
    };
  } catch (e) {
    console.error(e);
  }
}
