import Head from "next/head";
import styles from "../styles/Home.module.css";
import NavBar from "../components/navbar";
import FormSearch from "../components/formSearch";
import clientPromise from "../lib/mongodb";

export default function Home({ questions }) {
  return (
    <>
      <Head>
        <title>Home - App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className={styles.main}>
        <FormSearch _questions={questions[0].json} />
      </main>
    </>
  );
}

export async function getServerSideProps() {
  try {
    const client = await clientPromise;
    const db = client.db("fairsichern");

    const questions = await db
      .collection("questions")
      .find({})
      .sort({ _id: -1 })
      .limit(1)
      .toArray();

    return {
      props: { questions: JSON.parse(JSON.stringify(questions)) },
    };
  } catch (e) {
    console.error(e);
  }
}
