import Head from "next/head";
import styles from "../styles/Home.module.css";
import NavBar from "../components/navbar";
import clientPromise from "../lib/mongodb";

import AppointmentList from "../components/list/appointment";

export default function Kalender({ appointments }) {
  const appointmentsJSON = JSON.parse(appointments);
  return (
    <>
      <Head>
        <title>Kalender</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className={styles.main}>
        {/* <AppointmentList appointments={appointments} /> */}
      </main>
    </>
  );
}

export async function getServerSideProps() {
  try {
    const client = await clientPromise;
    const db = client.db("swe-projekt");

    const appointments = await db
      .collection("termine")
      .find({})
      .sort({ _id: -1 })
      .toArray();

    return {
      props: {
        appointments: JSON.stringify(appointments),
      },
    };
  } catch (e) {
    console.error(e);
  }
}
