import Head from "next/head";
import styles from "../styles/Home.module.css";
import NavBar from "../components/navbar";
import CustomerList from "../components/customer_list";
import clientPromise from "../lib/mongodb";

export default function Kalender({ customers, caregivers }) {
  const customersJSON = JSON.parse(customers);
  const caregiversJSON = JSON.parse(caregivers);
  return (
    <>
      <Head>
        <title>Kalender</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className={styles.main}>
        <CustomerList customers={customers} />
      </main>
    </>
  );
}

export async function getServerSideProps() {
  try {
    const client = await clientPromise;
    const db = client.db("swe-projekt");

    const customers = await db
      .collection("kunde")
      .find({})
      .sort({ _id: -1 })
      .toArray();

    const caregivers = await db
      .collection("pflegekraft")
      .find({})
      .sort({ _id: -1 })
      .toArray();

    return {
      props: {
        customers: JSON.stringify(customers),
        caregivers: JSON.stringify(caregivers),
      },
    };
  } catch (e) {
    console.error(e);
  }
}
