import Head from "next/head";
import styles from "../styles/Home.module.css";
import toolbar from "../styles/Toolbar.module.css";
import NavBar from "../components/navbar";
import CustomerList from "../components/customer_list";
import clientPromise from "../lib/mongodb";

export default function Kontakte({ customers, caregivers }) {
  const customersJSON = JSON.parse(customers);
  const caregiversJSON = JSON.parse(caregivers);
  return (
    <>
      <Head>
        <title>Kontakte</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className={styles.main}>
        <div className={toolbar.container}>
          <div className={toolbar.buttonContainer}>
            <div className={toolbar.searchContainer}>
              <div className={toolbar.textInput}>
                <input type="text" placeholder="Nach Einträgen suchen..." />
              </div>
              <div className={toolbar.searchButton}>Suchen</div>
            </div>
            <div className={toolbar.buttons}>
              <div className={toolbar.newButton}>+ Neu</div>
              <div className={toolbar.editButton}>Bearbeiten</div>
              <div className={toolbar.deleteButton}>Löschen</div>
            </div>
          </div>
        </div>
        <CustomerList customers={customers} />
      </main>
    </>
  );
}

export async function getServerSideProps() {
  try {
    const client = await clientPromise;
    const db = client.db("swe-projekt");

    const customers = await db
      .collection("kunde")
      .find({})
      .sort({ _id: -1 })
      .toArray();

    const caregivers = await db
      .collection("pflegekraft")
      .find({})
      .sort({ _id: -1 })
      .toArray();

    return {
      props: {
        customers: JSON.stringify(customers),
        caregivers: JSON.stringify(caregivers),
      },
    };
  } catch (e) {
    console.error(e);
  }
}
